// <auto-generated />
namespace OdeToFood.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RestaurantReview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RestaurantReview));
        
        string IMigrationMetadata.Id
        {
            get { return "201404211939120_RestaurantReview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
